// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/ohhfishal/schedule/lib/recurrence"
)

type Event struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Recurrence  *recurrence.Rule `json:"recurrence"`
	StartTime   int64            `json:"start_time"`
	EndTime     int64            `json:"end_time"`
}
